name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: all_workflows

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8 x_notes

      - name: Run black
        run: poetry run black x_notes --check

      - name: Run isort
        run: poetry run isort x_notes -c --profile black

      - name: Run tests
        run: poetry run pytest tests

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout previous version
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy files into place
        run: cp -r output/* gh-pages

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
          single-commit: false
