name: Fetch tweets

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */1 * * *"

permissions:
  contents: write

concurrency:
  group: all_workflows

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Checkout previous version
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: previous

      - name: Move data into place
        run: mv previous/data/notes.json output/data

      - name: Fetch tweets
        run: python -m x_notes.fetch_tweets
        env:
          UPDATE_SECRET: 1
          TWS_RAISE_WHEN_NO_ACCOUNT: 1
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          EMAIL: ${{ secrets.EMAIL }}
          PROXY: ${{ secrets.PROXY }}
          COOKIES: ${{ secrets.COOKIES }}
          REPO: ${{ github.repository }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          single-commit: true
