name: Fetch notes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Checkout previous version
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: previous

      - name: Move data into place
        run: mv previous/data/notes.json static/data

      - name: Fetch notes
        run: python -m x_notes

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static
          single-commit: true
