name: Fetch candidates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

concurrency:
  group: all_workflows

jobs:
  fetch:
    name: Fetch candidates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Install dependencies
        run: poetry install --only main

      - name: Checkout previous version
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: previous

      - name: Copy files into place
        run: cp -r previous/* output

      - name: Fetch candidates
        run: poetry run python -m x_notes.fetch_candidates

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          single-commit: true
