name: Fetch tweets

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

concurrency:
  group: all_workflows

jobs:
  fetch:
    name: Fetch tweets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Checkout previous version
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: previous

      - name: Copy files into place
        run: cp -r previous/* output

      - name: Fetch tweets
        run: python -m x_notes.fetch_tweets
        env:
          TW_USER: ${{ secrets.USER }}
          TW_PASS: ${{ secrets.PASS }}
          TW_EMAIL: ${{ secrets.EMAIL }}
          TW_PROXY: ${{ secrets.PROXY }}
          TW_COOKIES: ${{ secrets.COOKIES }}
          GH_UPDATE_SECRET: 1
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          single-commit: true
