name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Checkout output
      #   uses: actions/checkout@v4
      #   with:
      #     ref: gh-pages
      #     path: output

      - name: Fetch notes
        run: python -m x_notes

      # - name: Fetch tweets
      #   run: python -m x_notes.fetch_tweets
      #   env:
      #     TWS_RAISE_WHEN_NO_ACCOUNT: 1
      #     USER: ${{ secrets.USER }}
      #     PASS: ${{ secrets.PASS }}
      #     EMAIL: ${{ secrets.EMAIL }}
      #     PROXY: ${{ secrets.PROXY }}
      #     COOKIES: ${{ secrets.COOKIES }}
      #   continue-on-error: true

      - name: Move files into place
        run: cp -r static output

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          single-commit: true
